### PR TITLE
Major Code Reorganization Effort

### PR DESCRIPTION
**Pull request by LukeCroteau**
One of the downsides of using Flask "out of the box default" is that it's very easy to make a couple of messes without realizing it.

- After a lot of effort, the routes file tends to bloat from every endpoint/method being created there
- It's easy to create circular logic when referencing Data Models inside of Functionality blocks from other Data Models (e.g. Tournaments model needs to import Players, Players needs to import Tournaments)
- Adding functionality (like some off the current issue list), it's unclear where some of the work needs to be done. Setting boundaries for Where code belongs makes it a lot easier to get help for harder processes.
- Testing should be separated outside the normal bounds of the code (pytest, for example, looks for tests directories to execute)

This is a quick first pass at modifying the Tournaments information, and separating the Business Logic from the Data Models.
- Move the Data Model into a new `data_models` directory, and the Business Logic into a `business_logic` directory.
- Initialize the blueprints system.
- Move some of the Routes related to tournaments into the `blueprints` directory.
- Move the Simulation utility into the `tests` directory, for future Unit/Integration testing separation

**There are some Downsides to this**
- Some history of modifications is lost during the splitting of files. Since we're relocating chunks of code, the early history gets unlinked. Since this repository and codebase are very early, it shouldn't be a major concern.
- It looks like a LOT of files. We're definitely splitting code that used to be in 1 python module into multiple different modules, but for longevity of code and easier maintenance, it's crucial to organize things.

**The upsides here are pretty big, however**
- With the code separated more cleanly, it allows future developers to focus in on the areas they care about. (When I want to add functionality to a tournament, I don't have to scroll through lines of Data Models or code for top cuts, if I just want to, for example, link Decklists)
- Once everything is separated, multiple people creating MRs will have less chance of merge conflicts. That leads to less chances of trampling over each other's work when we're all implementing features and fixes.
- Bug fixes become more traceable. It becomes easier to target fixes in the places they're needed, again, without having to scroll through extraneous code.

### CODE REVIEW

**Comment by LukeCroteau** [comment]
If there's a file I haven't changed, at this point, I want it shot!

**Comment by LukeCroteau** [comment]
A note:
I didn't fully clean up all the Routes yet. This PR covers about 95% of the work that needs to be done.
I stopped doing routes because... I think there's a second wave of reorganization that probably needs to happen, to shift some of the `render_template` endpoints into a `views` segment.

At some point in the future, I'd like to remove some of the really hard `render_template` items to be Restful. Instead of embedding Python code into the html templates, I'd rather that happens as asynchronus Javascript. It works better for clients, and makes pages feel responsive.

**Comment by LukeCroteau** [comment]
Commit 07b5fb8 fixes #16

**Review by Chemscribbler — APPROVED** [review]
This looks great - I'll probably ask you to update the startup docs so people (me) know how to run this from the docker container :D

**Pull request merged**
